Implementation;Place and Route;RootName:FFT_Accel_system
Implementation;Place and Route||(null)||Please refer to the log file for details about 9 Info(s)||FFT_Accel_system_layout_log.log;liberoaction://open_report/file/FFT_Accel_system_layout_log.log||(null);(null)
HelpInfo,C:\Microsemi\Libero_SoC_v12.4\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v12.4\SynplifyPro\bin\mbin\assistant
